### ISSUE TITLE
Mandelbrot example not working

### ISSUE THREAD

**Issue by Pixdigit** [azul3d/examples#14]
It might just be my fault since I am new to GO but when I clone the mandelbrot example and `go run azul3d_mandel.go` it crashes with `./azul3d_mandel.go:72: undefined: Mandelbrot`

**Comment by slimsag** [comment]
`go run` only runs the named files. There are multiple Go files in the `azul3d_mandel` example, so you'll need to specify them all (`go run azul3d_mandel.go mandelbrot.go`) or better, just use `go build` inside that directory to produce the binary and run it with `./azul3d_mandel`
